import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import 'normalize.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import { ConfigProvider } from '@/components';
import { App } from 'antd';
const geistSans = Roboto({
  variable: "--font-roboto",
  subsets: ["latin", 'cyrillic'],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={geistSans.className}>
        <AntdRegistry>
          <ConfigProvider>
            <App>
              {children}
            </App>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
